### ISSUE TITLE
ResetLazySingleton: disposing function never called.

### ISSUE THREAD

**Issue by dannymanjon** [fluttercommunity/get_it#97] opened 2020-07-22 04:46 UTC
Try to reset a lazy singleton providing a disposing function. The function its never called, after checking the implementation of get_it I notice the following:
at line 732, InstanceFactory.instance its set to null, then at line 736 the condition tests the instance to check if its null to call the disposing function, but the issue its the instance has been already set to null, so the disposing function will never be called

`instanceFactory.instance = null;
    instanceFactory.pendingResult == null;
    instanceFactory._readyCompleter = Completer();

    if (instanceFactory.instance != null) {
      disposingFunction?.call(instanceFactory.instance as T);
    }`

**Comment by Sirrr** [comment] 2020-07-22 08:32
Duplicate of #92
Yes there is an issue. Is this project no more maintained?...

**Comment by escamoteur** [comment] 2020-07-22 09:16
@Sirrr uhm, maybe I was on vacation and do this in my free time?

**Comment by Sirrr** [comment] 2020-07-22 09:35
@escamoteur Sure, it's understandable. Happy to see that it is maintained.

**Comment by escamoteur** [comment] 2020-07-22 19:28
fixed in V4.0.4

**Closed by escamoteur** 2020-07-22 19:28 UTC
