### ISSUE TITLE
named instances breaking duo new asset

### ISSUE THREAD

**Issue by jhionan** [fluttercommunity/get_it#19] opened 2019-09-04 20:36 UTC
line 108 of commit #7209f1b89029fa01080b8f6119f8a391321c53b9  is aways false on named instances

**Comment by jhionan** [comment] 2019-09-04 20:38
Also changing positional parameter of named instances to named parameter causes break changes

**Comment by escamoteur** [comment] 2019-09-06 10:35
Hi.

yeah but the breaking change concerns only named parameters and there aren't many people using them right now :-)

I could not reproduce your problem, the tests all run through.
Could you post your code?
I also could not locate the line that you mentioned.
Cheers
Thomas

**Comment by rochadaniel** [comment] 2019-09-28 21:44
Hi Tomas. I was able to reproduce from the following code:
```dart
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';

final getIt = GetIt.instance;

class ApiHelper {
  String get nodeApi {
    return "node...";
  }

  String get phpApi {
    return "php...";
  }
}

void initGetIt() {
  getIt.registerLazySingleton(() => ApiHelper().nodeApi, instanceName: "node");
  getIt.registerLazySingleton(() => ApiHelper().phpApi, instanceName: "php");

  getIt.registerLazySingleton<MyRepository>(
      () => MyRepositoryImpl(api: getIt.get("node"))
  );

  getIt.registerFactory(() => MyUsecase(getIt()));
}

abstract class MyRepository {
  String getResult();
}

class MyRepositoryImpl implements MyRepository {
  final String api;

  MyRepositoryImpl({
  @required this.api
  });

  @override
  String getResult() {
    return "Result $api";
  }
}

class MyUsecase {
  final MyRepository myRepository;

  MyUsecase(this.myRepository);

  String getResult() {
    return myRepository.getResult();
  }
}

void main() {
  initGetIt();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Text(getIt<MyUsecase>().getResult()),
    );
  }
}
```

When I replace `final String api` with `final api` in `MyRepositoryImpl`, it works normally.

**Comment by escamoteur** [comment] 2019-10-23 12:42
Found it it was a caused because a wrong type was inferred. Fixed in next version

**Closed by escamoteur** 2019-10-23 12:42 UTC
Labels: waiting for customer response
