### ISSUE TITLE
Only on Web: NoSuchMethodError: method not found: 'pendingResult' on null

### ISSUE THREAD

**Issue by codekeyz** [fluttercommunity/get_it#215] opened 2021-07-09 19:15 UTC
I get this error when i run my flutter web app in release or profile mode.

Any ideas?

![Screenshot 2021-07-09 at 7 13 59 PM](https://user-images.githubusercontent.com/22515508/125125931-daee8a80-e0e9-11eb-85e9-f8da0a19c8e6.png)

**Comment by escamoteur** [comment] 2021-07-13 12:16
it only happens on web? Can you create a small repro project? unfortunately I can't see from that stacktrace where it happens insise get_it.

**Comment by escamoteur** [comment] 2021-07-13 12:32
which get_it version are you using?
I just hat a look through my code and this should not be possible normally. That is only happens in profile or release feels more like a compiler bug but I would need to run the code myself.

**Comment by escamoteur** [comment] 2021-07-13 15:07
It would really be great if you could reproduce this bug in a small repro project.

**Comment by quetool** [comment] 2021-08-17 14:48
Unfortunately I can't provide minimal reproducible bug right now but I have a similar issue.

![imgpsh_mobile_save](https://user-images.githubusercontent.com/14978705/129748343-e7ab227c-bbe6-4547-b47f-a95ee130b199.jpg)

**Comment by quetool** [comment] 2021-08-18 13:25
Ok, now I am getting the very same error of `pendingResult`

![Captura de pantalla 2021-08-18 a las 15 22 24](https://user-images.githubusercontent.com/14978705/129905804-5cb85fcd-3a54-430d-bb62-dd4ebcd66fb0.png)

I am using `get_it: ^7.1.3`

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale es-ES)
    • Flutter version 2.2.3 at /Users/alfredo.rinaudo/Development/SDKs/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alfredo.rinaudo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 90CEC436-D8AA-489D-A389-E56C67BEB9F2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

**Comment by quetool** [comment] 2021-08-25 07:12
So @codekeyz I fixed this error by replacing the way I was using the plugin.

I was getting the instance like this `final getIt = GetIt.instance;` on every class and then I was using like this notation: `getIt<MyDependencyModule>()`

So I deleted the first sentence `final getIt = GetIt.instance;` and now I am using the shortcut `GetIt.I` like this `GetIt.I<MyDependencyModule>()` .

This fixed the issue for me.

**Comment by bohdan1krokhmaliuk** [comment] 2022-01-17 11:01
I have the same issue at profile/release mode. In debug - everything works fine.
Also looks like there are some issues duplicating this one. @escamoteur is still anybody working on it?
![image](https://user-images.githubusercontent.com/59435984/149757910-fe1f0098-a13b-4c6c-9712-0319bef7df6c.png)

**Comment by escamoteur** [comment] 2022-02-02 11:35
Hi @bohdan1krokhmaliuk does the workaround work for you?

looking at your stacktrace it seems to be another problem than the others.

Without a repro project unfortunately I can't do that much

**Comment by escamoteur** [comment] 2022-02-02 11:39
Hi @kevmoo, there seems to be a bug in the web compiler. Not sure if you can already detect something from the stacktraces and reports above

**Comment by kevmoo** [comment] 2022-02-02 17:13
It seems like a `null` is getting in there somewhere. Not sure if it's a compiler issue or a code issue.

Is there a reproduction hosted somewhere we could check?

**Comment by escamoteur** [comment] 2022-02-02 17:15
Trying to get one
Am 2. Feb. 2022, 18:13 +0100 schrieb Kevin Moore ***@***.***>:

**Comment by escamoteur** [comment] 2022-02-04 10:02
duplicate of https://github.com/fluttercommunity/get_it/issues/238

the generated JS code doesn't make any sense

**Closed** 2022-02-04 10:02 UTC
Labels: bug, web
